--insert into Alien values (1,'Ravi','Java');
--insert into Alien values (2,'Swati','C++');
--insert into Alien values (3,'Abhishek','Java');
--insert into Alien values (4,'Rupya','Python');
--insert into Alien values (5,'Kala','Dot Net');
--insert into Alien values (6,'Amit','Java');